stages:
  - build
  - publish

build:
  stage: build
  image: mhart/alpine-node:8
  script:
  - npm install
  - npm run build

publish:
  stage: publish
  image: mhart/alpine-node:8
  script:
  - npm install
  - npx npm-cli-login -u "$NPM_USER" -p "$NPM_PASS" -e "$NPM_EMAIL" -s "$NPM_SCOPE"
  - npm run make-distribution
  - cd lib/main
  - npm publish --access public
  only:
    - /^([0-9]{1,}\.[0-9]{1,}\.[0-9]{1,}(-(pre|rc)\.[0-9]{1,})?)$/
