.authenticate-to-npmjs:
  - &authenticate-to-npmjs |
      echo "@northscaler:registry=https://$NPM_REGISTRY_HOST/" >> ~/.npmrc
      echo "//$NPM_REGISTRY_HOST/:_authToken=$NPM_AUTH_TOKEN" >> ~/.npmrc

stages:
  - build
  - publish

build:
  stage: build
  image: mhart/alpine-node:8
  script:
  - npm install
  - npm run build

publish:
  stage: publish
  image: mhart/alpine-node:8
  script:
  - *authenticate-to-npmjs
  - cat ~/.npmrc
  - npm install
  - npm run make-distribution
  - cd lib/main
  - npm publish --access public
  only:
    - /^([0-9]{1,}\.[0-9]{1,}\.[0-9]{1,}(-(pre|rc)\.[0-9]{1,})?)$/
